version: '3.5'

services:
    frontend:
      image: front
      container_name: frontend
    backend:
      image: back
      container_name: backend
      environment:
        - REDIS=redis_container
        - DB_HOST=db
        - DB_PASSWORD=secret
        - DB_USERNAME=user
        - DB_NAME=db
    proxy:
      image: jwilder/nginx-proxy
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - /var/run/docker.sock:/tmp/docker.sock:ro
      ports:
        - 80:80
      environment:
        - NGINX_PORT=80
      container_name: proxy
      depends_on:
        - backend
    redis:
      image: redis
      container_name: redis_container
    db:
      image: postgres
      restart: unless-stopped
      environment:
        - POSTGRES_PASSWORD=secret
        - POSTGRES_USER=user
        - POSTGRES_DB=db
      container_name: db

