version: '3.5'

services:
    frontend:
      image: front
      ports:
        - 5000:5000
    backend:
      image: back
      container_name: backend_container
      ports:
        - 8000:8000
      environment:
        - REDIS=redis_container
    redis:
      image: redis
      container_name: redis_container


